import { useState } from 'react';
import './index.css';

const CLINICIAN_SCENARIOS = [
  { id:"discharge", title:"Discharge instructions", diff:"Core", color:"#0A84FF", bg:"rgba(10,132,255,.12)", desc:"Deliver post-procedure care instructions at appropriate health literacy level.", script:"You are speaking with a patient being discharged after a procedure. Cover: (1) wound care at home, (2) medication name, dose, and schedule, (3) three warning signs requiring emergency care, and (4) follow-up appointment details. Aim 60-90 seconds. Use plain language a 6th-grade reading level would understand.", rubric:[{id:"clarity",l:"Plain language clarity",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"confidence",l:"Confidence signal",w:.20},{id:"composure",l:"Vocal composure",w:.20},{id:"fillers",l:"Filler word control",w:.15}]},
  { id:"consent", title:"Informed consent", diff:"Core", color:"#0A84FF", bg:"rgba(10,132,255,.12)", desc:"Explain a procedure and confirm verbal consent using plain language and teach-back.", script:"Explain the upcoming procedure, describe main risks and benefits in plain language, and ask the patient to confirm understanding and consent. Use the teach-back method. Speak at a calm, unhurried pace.", rubric:[{id:"clarity",l:"Plain language clarity",w:.25},{id:"empathy",l:"Empathic tone",w:.20},{id:"pace",l:"Pace and pacing",w:.20},{id:"confidence",l:"Confidence signal",w:.20},{id:"fillers",l:"Filler word control",w:.15}]},
  { id:"triage", title:"Triage intake", diff:"Advanced", color:"#FF6B35", bg:"rgba(255,107,53,.12)", desc:"Conduct rapid triage gathering key clinical information efficiently and calmly.", script:"Conduct a triage intake. Ask about chief complaint, onset and duration, pain scale 0-10, relevant history, and current medications. Stay efficient, calm, and professional. Reflect back what you hear. Aim for 90 seconds.", rubric:[{id:"efficiency",l:"Efficient questioning",w:.25},{id:"calm",l:"Calm under pressure",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"confidence",l:"Confidence signal",w:.15},{id:"fillers",l:"Filler word control",w:.15}]},
  { id:"mental", title:"Mental health disclosure", diff:"Advanced", color:"#FF6B35", bg:"rgba(255,107,53,.12)", desc:"Respond empathically to a patient disclosing depression and self-harm thoughts.", script:"A patient has disclosed depressive episodes and thoughts of self-harm. Respond with empathy and without alarm. Acknowledge their courage in sharing, ask a clarifying question, explain next steps in care, and reassure of confidentiality. Speak slowly and warmly.", rubric:[{id:"empathy",l:"Empathic tone",w:.30},{id:"calm",l:"Calm composure",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"confidence",l:"Grounded confidence",w:.15},{id:"fillers",l:"Filler word control",w:.10}]},
  { id:"interp-open", title:"Interpreter role opening", diff:"Core", color:"#BF5AF2", bg:"rgba(191,90,242,.12)", desc:"Open a medical encounter as interpreter, introduce your role, set ground rules.", script:"You are a medical interpreter beginning an interpreted clinical encounter. Introduce yourself to both provider and patient, explain the interpreter role and confidentiality, ask both parties to speak in short segments, and establish direct communication norms. Demonstrate professionalism and neutrality.", rubric:[{id:"clarity",l:"Role clarity",w:.25},{id:"neutrality",l:"Professional neutrality",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"confidence",l:"Confidence signal",w:.20},{id:"fillers",l:"Filler word control",w:.10}]},
  { id:"interp-intervene", title:"Interpreter intervention", diff:"Advanced", color:"#BF5AF2", bg:"rgba(191,90,242,.12)", desc:"Handle a communication breakdown requiring professional assertiveness.", script:"The provider has used a clinical term the patient clearly does not understand, and the patient is nodding without comprehension. As interpreter, pause the encounter, explain your intervention to the provider, request clarification, and resume. Demonstrate assertiveness without overstepping your role.", rubric:[{id:"assertiveness",l:"Professional assertiveness",w:.30},{id:"neutrality",l:"Role boundary maintenance",w:.25},{id:"pace",l:"Pace and composure",w:.20},{id:"confidence",l:"Confidence signal",w:.15},{id:"fillers",l:"Filler word control",w:.10}]},
];

const PATIENT_SCENARIOS = [
  { id:"p-symptoms", title:"Describing symptoms", diff:"Core", color:"#30D158", bg:"rgba(48,209,88,.12)", desc:"Practice describing your symptoms clearly so your provider understands.", script:"Practice telling your doctor about a health concern. Describe when it started, what makes it worse or better, how it affects your daily life, and any other symptoms you've noticed. Be specific. Speak clearly and confidently.", rubric:[{id:"clarity",l:"Symptom clarity",w:.30},{id:"confidence",l:"Self-advocacy confidence",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"detail",l:"Detail and specificity",w:.15},{id:"fillers",l:"Filler word control",w:.10}]},
  { id:"p-questions", title:"Asking questions", diff:"Core", color:"#30D158", bg:"rgba(48,209,88,.12)", desc:"Practice asking your provider questions about your diagnosis or treatment.", script:"You've just received a diagnosis. Practice asking your provider: What does this diagnosis mean? What are my treatment options? What happens if I do nothing? What should I watch for at home? Speak up clearly and don't let yourself be rushed.", rubric:[{id:"confidence",l:"Self-advocacy confidence",w:.30},{id:"clarity",l:"Question clarity",w:.25},{id:"pace",l:"Pace and pacing",w:.20},{id:"assertiveness",l:"Assertive communication",w:.15},{id:"fillers",l:"Filler word control",w:.10}]},
  { id:"p-medication", title:"Medication concerns", diff:"Advanced", color:"#FFD60A", bg:"rgba(255,214,10,.10)", desc:"Communicate concerns or side effects about a prescribed medication.", script:"You have concerns about a medication you've been prescribed. Practice telling your provider: what side effects you're experiencing, how they're affecting your daily life, and what you'd like to happen next. Be direct and advocate for yourself without dismissing the prescription.", rubric:[{id:"confidence",l:"Self-advocacy confidence",w:.30},{id:"assertiveness",l:"Assertive communication",w:.25},{id:"clarity",l:"Concern clarity",w:.25},{id:"pace",l:"Pace and pacing",w:.10},{id:"fillers",l:"Filler word control",w:.10}]},
  { id:"p-consent", title:"Responding to consent", diff:"Advanced", color:"#FFD60A", bg:"rgba(255,214,10,.10)", desc:"Practice confirming or requesting clarification before consenting to a procedure.", script:"Your provider has just explained a procedure and asked for your consent. Practice responding by confirming what you understood, asking at least one clarifying question about a risk or alternative, and stating your decision clearly. You have the right to take your time.", rubric:[{id:"confidence",l:"Self-advocacy confidence",w:.25},{id:"clarity",l:"Response clarity",w:.25},{id:"assertiveness",l:"Assertive communication",w:.25},{id:"pace",l:"Pace and pacing",w:.15},{id:"fillers",l:"Filler word control",w:.10}]},
];

const READINESS = [
  {min:0,max:49,label:"Needs development",color:"#FF453A",bg:"rgba(255,69,58,.12)"},
  {min:50,max:64,label:"Developing",color:"#FF9F0A",bg:"rgba(255,159,10,.10)"},
  {min:65,max:79,label:"Approaching ready",color:"#FF9F0A",bg:"rgba(255,159,10,.10)"},
  {min:80,max:89,label:"Ready",color:"#30D158",bg:"rgba(48,209,88,.12)"},
  {min:90,max:100,label:"Proficient",color:"#34C759",bg:"rgba(52,199,89,.15)"},
];

const ROLES_C = ["Physician","Nurse","Nurse Practitioner","Physician Assistant","Medical Interpreter","Pharmacist","Social Worker","Healthcare Administrator","Other Clinician"];
const ROLES_P = ["Patient","Caregiver / Family member","Patient advocate","Other"];

function autoCorr(buf,sr){const SIZE=buf.length,half=Math.floor(SIZE/2);let rms=0;for(let i=0;i<SIZE;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/SIZE);if(rms<0.01)return -1;let best=-1,bc=0,lc=1,found=false;for(let off=0;off<half;off++){let c=0;for(let i=0;i<half;i++)c+=Math.abs(buf[i]-buf[i+off]);c=1-c/half;if(c>0.9&&c>lc){found=true;bc=c;best=off;}else if(found)break;lc=c;}if(best===-1)return -1;const sh=Math.max(0,best-1),sh2=Math.min(half-1,best+1);let y1=0,y2=0;for(let i=0;i<half;i++){y1+=Math.abs(buf[i]-buf[i+sh]);y2+=Math.abs(buf[i]-buf[i+sh2]);}y1=1-y1/half;y2=1-y2/half;return sr/(best+(y2-y1)/(2*(2*bc-y1-y2)));}

function doNLP(t){const txt=t||'',clean=txt.toLowerCase().replace(/[^a-z\s']/g,'');const words=clean.split(/\s+/).filter(w=>w.length>0);const FL=['um','uh','like','you know','basically','literally','right','so','well','actually','kind of','sort of','just'];let fc=0;FL.forEach(f=>{const m=txt.match(new RegExp(`\\b${f}\\b`,'gi'));if(m)fc+=m.length;});const ttr=words.length>5?Math.round(new Set(words).size/words.length*100):null;const awl=words.length?+(words.reduce((s,w)=>s+w.length,0)/words.length).toFixed(1):null;return{wc:words.length,ttr,fc,awl};}

function freshState(){return{volBuf:[],pitchBuf:[],winRates:[],winStart:null,winSyl:0,syl:0,spStart:null,pauses:0,lastSilent:false,drops:0,prevVol:null};}

function calcScores({volBuf,pitchBuf,winRates,syl,spStart,pauses,drops,freqData}){const av=volBuf.length?volBuf.reduce((a,b)=>a+b,0)/volBuf.length:-60;const vp=pitchBuf.filter(p=>p>0);const ap=vp.length?vp.reduce((a,b)=>a+b,0)/vp.length:0;const el=spStart?(Date.now()-spStart)/60000:0;const pace=el>0.05?Math.round(syl/el/1.5):0;const r20=vp.slice(-20);const pv=r20.length>2?Math.sqrt(r20.reduce((s,p)=>s+Math.pow(p-ap,2),0)/r20.length):0;const hi=el>0.1?Math.round(pauses/el):0;const ri=winRates.length>2?Math.sqrt(winRates.reduce((s,r)=>{const m=winRates.reduce((a,b)=>a+b,0)/winRates.length;return s+Math.pow(r-m,2);},0)/winRates.length):0;const hf=freqData?Array.from(freqData.slice(Math.floor(freqData.length*0.6))):[];const tension=hf.length?Math.min(100,(hf.reduce((a,b)=>a+b,0)/hf.length)*1.2):0;const pvS=Math.min(100,pv*1.5),hiS=Math.min(100,hi*6),riS=Math.min(100,ri*1.2),edS=Math.min(100,drops*2);const stress=Math.round((pvS+hiS+riS+edS+tension)/5);const load=Math.round(pvS*0.3+hiS*0.3+riS*0.2+tension*0.2);const fluency=Math.round(Math.max(0,Math.min(100,100-(pvS*0.3+hiS*0.3+edS*0.2+riS*0.2))));let conf=50;if(av>-30&&av<-5)conf+=15;else if(av<=-30)conf-=15;if(ap>85&&ap<260)conf+=10;if(pace>110&&pace<170)conf+=20;else if(pace>80&&pace<200)conf+=10;conf-=stress*0.15;conf=Math.round(Math.max(0,Math.min(100,conf)));return{conf,fluency,load,stress,avgVol:av,avgPitch:ap,pace,pvS,hiS,riS,edS,tension};}

function rubricScores(s,n){if(!s)return{};const pace=s.pace>110&&s.pace<170?90:s.pace>80&&s.pace<200?72:s.pace>0?50:0;const fillers=n?Math.max(0,100-n.fc*9):0;const composure=Math.round(Math.max(0,100-s.stress));const empathy=Math.round(Math.max(0,100-s.pvS*.4-s.hiS*.3));const clarity=Math.round(Math.min(100,(n?.ttr??50)*.5+s.conf*.5));const neutrality=Math.round(Math.max(0,90-s.stress*.4));const detail=Math.round(Math.min(100,n?.wc>25?85:60));return{pace,confidence:s.conf,composure,fillers,empathy,clarity,neutrality,assertiveness:Math.round(Math.min(100,s.conf+8)),efficiency:s.pace>120?88:65,calm:composure,detail};}

const sc=v=>v>=70?'#30D158':v>=45?'#FF9F0A':'#FF453A';
const stC=v=>v<30?'#30D158':v<60?'#FF9F0A':'#FF453A';
const getRL=s=>READINESS.find(r=>s>=r.min&&s<=r.max)||READINESS[0];
const loadLS=(k,fb)=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):fb;}catch{return fb;}};
const saveLS=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};

import { useState as uS, useRef as uR, useCallback as uC, useEffect as uE } from 'react';

function useAudio(){
  const R=uR({ac:null,an:null,src:null,stream:null,raf:null});
  const S=uR(freshState());
  const cvs=uR(null);
  const[scores,setScores]=uS(null);
  const[rec,setRec]=uS(false);
  function draw(d,n){const c=cvs.current;if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#0A84FF';ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<n;i++){const y=(d[i]/128)*H/2;i===0?ctx.moveTo(0,y):ctx.lineTo(i*(W/n),y);}ctx.stroke();}
  const tick=uC(()=>{R.current.raf=requestAnimationFrame(tick);const{an,ac}=R.current;if(!an||!ac)return;const s=S.current,N=an.fftSize;const td=new Float32Array(N),bt=new Uint8Array(N),fd=new Uint8Array(an.frequencyBinCount);an.getFloatTimeDomainData(td);an.getByteTimeDomainData(bt);an.getByteFrequencyData(fd);draw(bt,N);let rms=0;for(let i=0;i<N;i++)rms+=td[i]*td[i];rms=Math.sqrt(rms/N);const vol=rms>0.0001?20*Math.log10(rms):-80;const pitch=autoCorr(td,ac.sampleRate);const speech=vol>-42;s.volBuf.push(vol);if(s.volBuf.length>80)s.volBuf.shift();if(pitch>60&&pitch<500){s.pitchBuf.push(pitch);if(s.pitchBuf.length>80)s.pitchBuf.shift();}if(speech){if(!s.spStart)s.spStart=Date.now();s.syl+=0.025;if(!s.winStart){s.winStart=Date.now();s.winSyl=0;}s.winSyl+=0.025;if(Date.now()-s.winStart>5000){s.winRates.push(s.winSyl/((Date.now()-s.winStart)/60000)/1.5);if(s.winRates.length>8)s.winRates.shift();s.winStart=Date.now();s.winSyl=0;}if(s.lastSilent){s.pauses++;s.lastSilent=false;}if(s.prevVol!==null&&s.prevVol-vol>8)s.drops++;}else{if(!s.lastSilent)s.lastSilent=true;}s.prevVol=vol;setScores(calcScores({...s,freqData:fd}));},[]);
  const start=uC(async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ac=new(window.AudioContext||window.webkitAudioContext)();const an=ac.createAnalyser();an.fftSize=2048;const src=ac.createMediaStreamSource(stream);src.connect(an);R.current={ac,an,src,stream,raf:null};S.current=freshState();setScores(null);setRec(true);tick();return true;}catch(e){console.error('Mic error:',e);return false;}},[tick]);
  const stop=uC(()=>{const r=R.current;cancelAnimationFrame(r.raf);try{r.src?.disconnect();}catch{}try{r.stream?.getTracks().forEach(t=>t.stop());}catch{}try{r.ac?.close();}catch{}R.current={ac:null,an:null,src:null,stream:null,raf:null};setRec(false);},[]);
  return{scores,rec,start,stop,cvs};
}

function useSpeech(){
  const ref=uR(null),full=uR('');
  const[txt,setTxt]=uS('');
  const ok=!!(window.SpeechRecognition||window.webkitSpeechRecognition);
  const start=uC(()=>{if(!ok)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new SR();r.continuous=true;r.interimResults=true;r.lang='en-US';r.onresult=e=>{let f='',im='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)f+=e.results[i][0].transcript+' ';else im+=e.results[i][0].transcript;}if(f)full.current+=f;setTxt((full.current+im).trim());};r.onerror=()=>{};try{r.start();}catch{}ref.current=r;},[ok]);
  const stop=uC(()=>{try{ref.current?.stop();}catch{}ref.current=null;return full.current;},[]);
  const reset=uC(()=>{full.current='';setTxt('');},[]);
  return{txt,ok,start,stop,reset};
}

function Ring({v,label,color,size=86}){const R2=size*.38,C=2*Math.PI*R2,off=v!=null?C-(v/100)*C:C,c=color||(v!=null?sc(v):'rgba(255,255,255,.15)');return(<div style={{textAlign:'center'}}><svg width={size}height={size}viewBox={`0 0 ${size} ${size}`}><circle cx={size/2}cy={size/2}r={R2}fill="none"strokeWidth="5"stroke="rgba(255,255,255,.08)"/><circle cx={size/2}cy={size/2}r={R2}fill="none"strokeWidth="5"stroke={c}strokeLinecap="round"strokeDasharray={C}strokeDashoffset={off}transform={`rotate(-90 ${size/2} ${size/2})`}style={{transition:'stroke-dashoffset .5s,stroke .4s'}}/><text x={size/2}y={size/2+5}textAnchor="middle"fontSize={size*.2}fontWeight="600"fill="#f2f2f7"fontFamily="'DM Mono',monospace">{v!=null?Math.round(v):'--'}</text></svg><div style={{fontSize:10,color:'rgba(242,242,247,.4)',marginTop:1}}>{label}</div></div>);}

const Lbl=({children,mt=14})=><div style={{fontSize:9,fontWeight:700,letterSpacing:'.1em',textTransform:'uppercase',color:'rgba(242,242,247,.35)',marginBottom:7,marginTop:mt}}>{children}</div>;
const Card=({children,style})=><div style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.09)',borderRadius:14,padding:'13px 15px',...style}}>{children}</div>;
const RecBtn=({rec,onToggle})=>(<button onClick={onToggle}style={{display:'flex',alignItems:'center',gap:7,padding:'9px 18px',background:rec?'rgba(255,69,58,.12)':'rgba(255,255,255,.08)',border:`1px solid ${rec?'#FF453A':'rgba(255,255,255,.15)'}`,borderRadius:10,fontSize:13,fontWeight:600,color:rec?'#FF453A':'#f2f2f7',cursor:'pointer',transition:'all .15s'}}>{rec?<span style={{width:7,height:7,borderRadius:'50%',background:'#FF453A',animation:'blink 1s ease-in-out infinite',flexShrink:0}}/>:<span style={{width:7,height:7,borderRadius:'50%',background:'#FF453A',flexShrink:0}}/>}{rec?'Stop recording':'Start recording'}</button>);

function LivePage({profile,onEnd}){
  const{scores,rec,start,stop,cvs}=useAudio();
  const{txt,ok,start:startSR,stop:stopSR,reset:resetSR}=useSpeech();
  const n=doNLP(txt);const s=scores;
  const mC=profile.mode==='patient'?'#30D158':'#0A84FF';
  const toggle=async()=>{if(!rec){resetSR();const ok2=await start();if(!ok2)return alert('Microphone access denied. Please allow microphone access in your browser settings and try again.');startSR();}else{const ft=stopSR();stop();if(onEnd)onEnd({...scores,transcript:ft,nlp:doNLP(ft),type:'Free recording',scenario:null,mode:profile.mode});}};
  return(<div>
    <div style={{display:'flex',justifyContent:'space-around',marginBottom:'1rem',flexWrap:'wrap',gap:6}}><Ring v={s?.conf}label="Confidence"color={mC}/><Ring v={s?.fluency}label="Fluency"color="#BF5AF2"/><Ring v={s?.load}label="Cog. load"color={s?.load>60?'#FF453A':'#FF9F0A'}/><Ring v={s?.stress!=null?100-s.stress:null}label="Composure"color={sc(s?100-s.stress:50)}/></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:9,marginBottom:10}}>
      {[{l:'Volume',v:s?Math.round(s.avgVol):null,u:'dB',p:s?Math.min(100,(s.avgVol+60)/55*100):0,c:mC},{l:'Pitch',v:s?.avgPitch>0?Math.round(s.avgPitch):null,u:'Hz',p:s?(s.avgPitch/400)*100:0,c:'#BF5AF2'},{l:'Pace',v:s?.pace>0?s.pace:null,u:'wpm',p:s?(s.pace/200)*100:0,c:'#FF6B35'}].map(x=>(<div key={x.l}style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.09)',borderRadius:10,padding:'11px 13px'}}><div style={{fontSize:9,fontWeight:600,letterSpacing:'.08em',textTransform:'uppercase',color:'rgba(242,242,247,.35)',marginBottom:3}}>{x.l}</div><div><span style={{fontSize:18,fontWeight:600,fontFamily:"'DM Mono',monospace"}}>{x.v!=null?x.v:'--'}</span><span style={{fontSize:10,color:'rgba(242,242,247,.35)',marginLeft:2}}>{x.u}</span></div><div style={{height:3,background:'rgba(255,255,255,.07)',borderRadius:2,marginTop:7,overflow:'hidden'}}><div style={{height:'100%',width:`${Math.min(100,Math.round(x.p||0))}%`,background:x.c,borderRadius:2,transition:'width .35s'}}/></div></div>))}
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginBottom:10}}>
      {[{l:'Pitch volatility',v:s?.pvS},{l:'Hesitation',v:s?.hiS},{l:'Rate consistency',v:s?.riS},{l:'Vocal tension',v:s?.tension}].map(x=>{const p=Math.min(100,Math.round(x.v||0)),c=stC(p);return(<div key={x.l}style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.09)',borderRadius:10,padding:'10px 12px'}}><div style={{fontSize:9,fontWeight:600,letterSpacing:'.07em',textTransform:'uppercase',color:'rgba(242,242,247,.35)',marginBottom:3}}>{x.l}</div><div style={{display:'flex',alignItems:'center',gap:7}}><span style={{fontSize:13,fontWeight:600,fontFamily:"'DM Mono',monospace",minWidth:26,color:c}}>{p}</span><div style={{flex:1,height:3,background:'rgba(255,255,255,.07)',borderRadius:2,overflow:'hidden'}}><div style={{height:'100%',width:`${p}%`,background:c,borderRadius:2,transition:'width .35s'}}/></div><span style={{fontSize:9,color:c,minWidth:24,textAlign:'right',fontWeight:600}}>{p<30?'low':p<60?'mod':'high'}</span></div></div>);})}
    </div>
    <div style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'9px 12px',marginBottom:10}}><canvas ref={cvs}width={640}height={44}style={{width:'100%',height:44,display:'block'}}/></div>
    <div style={{display:'flex',gap:10,alignItems:'center',marginBottom:10,flexWrap:'wrap'}}>
      <RecBtn rec={rec}onToggle={toggle}/><span style={{fontSize:12,color:'rgba(242,242,247,.4)'}}>{rec?'Analyzing...':'Click to begin session'}</span>
      {!ok&&<span style={{fontSize:10,color:'#FF9F0A'}}>Use Chrome or Edge for live transcription</span>}
    </div>
    <Lbl mt={0}>Live transcript</Lbl>
    <div style={{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'12px 14px',minHeight:52,marginBottom:10}}><p style={{fontSize:12,fontFamily:"'DM Mono',monospace",color:txt?'#f2f2f7':'rgba(242,242,247,.25)',lineHeight:1.7,wordBreak:'break-word',whiteSpace:'pre-wrap'}}>{txt||'Start recording to see live transcription...'}</p></div>
    <Lbl>Verbal signals</Lbl>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:8,marginBottom:12}}>
      {[{l:'Words',v:n.wc},{l:'Vocab diversity',v:n.ttr!=null?`${n.ttr}%`:'--'},{l:'Fillers',v:n.fc},{l:'Avg word len',v:n.awl??'--'}].map(c=>(<div key={c.l}style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'10px 12px',textAlign:'center'}}><div style={{fontSize:15,fontWeight:600,fontFamily:"'DM Mono',monospace"}}>{c.v}</div><div style={{fontSize:9,color:'rgba(242,242,247,.35)',marginTop:2,textTransform:'uppercase',letterSpacing:'.06em'}}>{c.l}</div></div>))}
    </div>
    <div style={{background:'rgba(255,159,10,.08)',border:'1px solid rgba(255,159,10,.2)',borderRadius:10,padding:'10px 13px'}}><p style={{fontSize:11,color:'rgba(255,214,10,.7)',lineHeight:1.7}}>Vocal signals reflect communication patterns and cognitive effort. They are not diagnostic and do not replace clinical judgment.</p></div>
  </div>);
}

function ScenarioPage({profile,onEnd}){
  const scenarios=profile.mode==='patient'?PATIENT_SCENARIOS:CLINICIAN_SCENARIOS;
  const[chosen,setChosen]=uS(0);const{scores,rec,start,stop,cvs}=useAudio();const{txt,start:startSR,stop:stopSR,reset:resetSR}=useSpeech();const[done,setDone]=uS(null);
  const sc2=scenarios[chosen];const activeTxt=rec?txt:(done?.transcript||'');const activeN=doNLP(activeTxt);const activeS=rec?scores:done?.scores;const rs=rubricScores(activeS,activeN);const overall=activeS?Math.round(sc2.rubric.reduce((a,r)=>a+(rs[r.id]||0)*r.w,0)):0;
  const toggle=async()=>{if(!rec){resetSR();setDone(null);const ok=await start();if(!ok)return alert('Microphone access denied.');startSR();}else{const ft=stopSR();stop();const n2=doNLP(ft);const rs2=rubricScores(scores,n2);const ov=Math.round(sc2.rubric.reduce((a,r)=>a+(rs2[r.id]||0)*r.w,0));setDone({scores,transcript:ft,nlp:n2,rubric:rs2,overall:ov});if(onEnd)onEnd({...scores,transcript:ft,nlp:n2,type:'Scenario',scenario:sc2.title,scenarioId:sc2.id,overallScore:ov,mode:profile.mode});}};
  return(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9,marginBottom:12}}>
      {scenarios.map((s2,i)=>(<div key={s2.id}onClick={()=>!rec&&setChosen(i)}style={{background:'rgba(255,255,255,.04)',border:`${chosen===i?`1.5px solid ${s2.color}`:'1px solid rgba(255,255,255,.09)'}`,borderRadius:12,padding:'12px 14px',cursor:rec?'default':'pointer',opacity:rec&&chosen!==i?.4:1,transition:'all .15s'}}><div style={{fontSize:13,fontWeight:600,marginBottom:3,color:'#f2f2f7'}}>{s2.title}</div><div style={{fontSize:11,color:'rgba(242,242,247,.45)',lineHeight:1.5,marginBottom:7}}>{s2.desc}</div><span style={{fontSize:9,fontWeight:700,padding:'2px 8px',borderRadius:10,background:s2.bg,color:s2.color}}>{s2.diff}</span></div>))}
    </div>
    <Lbl mt={0}>Script prompt</Lbl>
    <div style={{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'13px 15px',marginBottom:10}}><p style={{fontSize:12,fontFamily:"'DM Mono',monospace",lineHeight:1.85,color:'#f2f2f7'}}>{sc2.script}</p></div>
    <div style={{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'9px 12px',marginBottom:10}}><canvas ref={cvs}width={640}height={40}style={{width:'100%',height:40,display:'block'}}/></div>
    <div style={{display:'flex',gap:10,alignItems:'center',marginBottom:10,flexWrap:'wrap'}}><RecBtn rec={rec}onToggle={toggle}/><span style={{fontSize:12,color:'rgba(242,242,247,.4)'}}>{rec?`Practicing: ${sc2.title}`:done?'Done. Select or retry.':'Select a scenario, then record'}</span></div>
    <Lbl>Transcript</Lbl>
    <div style={{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'12px 14px',minHeight:48,marginBottom:10}}><p style={{fontSize:12,fontFamily:"'DM Mono',monospace",color:activeTxt?'#f2f2f7':'rgba(242,242,247,.25)',lineHeight:1.7,wordBreak:'break-word',whiteSpace:'pre-wrap'}}>{activeTxt||'Your speech will appear here...'}</p></div>
    <Lbl>Scenario rubric</Lbl>
    <Card>{sc2.rubric.map(r=>(<div key={r.id}style={{display:'flex',alignItems:'center',gap:10,padding:'7px 0',borderBottom:'1px solid rgba(255,255,255,.06)'}}><span style={{fontSize:12,minWidth:170,color:'#f2f2f7'}}>{r.l}</span><div style={{flex:1,height:5,background:'rgba(255,255,255,.07)',borderRadius:3,overflow:'hidden'}}><div style={{height:'100%',width:`${Math.min(100,rs[r.id]||0)}%`,background:sc(rs[r.id]||0),borderRadius:3,transition:'width .5s'}}/></div><span style={{fontFamily:"'DM Mono',monospace",fontSize:11,color:'rgba(242,242,247,.4)',minWidth:24,textAlign:'right'}}>{Math.round(rs[r.id]||0)}</span></div>))}{(done||rec)&&overall>0&&(<div style={{marginTop:10,paddingTop:10,borderTop:'1px solid rgba(255,255,255,.07)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:12,color:'rgba(242,242,247,.4)'}}>Weighted overall score</span><span style={{fontFamily:"'DM Mono',monospace",fontSize:18,fontWeight:600,color:sc(overall)}}>{overall}</span></div>)}</Card>
  </div>);
}

function CoachPage({last,profile}){
  const[report,setReport]=uS('');const[loading,setLoading]=uS(false);const[err,setErr]=uS('');
  const gen=async()=>{if(!last)return;setLoading(true);setErr('');setReport('');const s=last;const isPatient=s.mode==='patient'||profile.mode==='patient';
    const prompt=`You are a healthcare communication coach. Write a personalized coaching report.\n\nRole: ${profile.role||profile.mode}\nSession: ${s.type}${s.scenario?` (${s.scenario})`:''}${isPatient?' — patient communication coaching':' — clinician/interpreter coaching'}\n\nMetrics: Confidence ${s.conf}/100, Fluency ${s.fluency}/100, Cognitive load ${s.load}/100, Stress ${s.stress}/100, Pace ${s.pace} wpm, Fillers ${s.nlp?.fc||0}${s.overallScore?`, Scenario score ${s.overallScore}/100`:''}\n${s.transcript?`Transcript: "${s.transcript.substring(0,300)}"`:''}\n\nWrite exactly 4 plain paragraphs. No headers, bullets, markdown. 1) One genuine strength. 2) Top improvement area with specific behavioral guidance. 3) One drill for next 24 hours. 4) Encouragement tied to their healthcare context. Warm, direct, professional. ${isPatient?'Patient mode: be empowering.':'Clinician mode: hold to high clinical communication standard.'}`;
    try{let txt=null;for(const url of['https://api.anthropic.com/v1/messages','/api/claude']){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:800,messages:[{role:'user',content:prompt}]})});if(!r.ok)continue;const d=await r.json();txt=d.content?.find(b=>b.type==='text')?.text;if(txt)break;}catch{continue;}}if(txt)setReport(txt);else setErr('AI coaching requires an Anthropic API connection.');}catch{setErr('Network error.');}setLoading(false);};
  if(!last)return(<div style={{textAlign:'center',padding:'3rem 1rem',color:'rgba(242,242,247,.3)'}}><div style={{fontSize:28,marginBottom:10}}>◎</div><p style={{fontSize:13}}>Complete a recording session to generate your coaching report.</p></div>);
  const s=last;const rl=getRL(s.overallScore||s.conf);const isInterp=s.scenarioId?.includes('interp');
  return(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:8,marginBottom:14}}>{[{l:'Confidence',v:s.conf},{l:'Fluency',v:s.fluency},{l:'Stress',v:s.stress},{l:'Pace',v:s.pace>0?s.pace:'--'}].map(c=>(<div key={c.l}style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'10px 12px',textAlign:'center'}}><div style={{fontFamily:"'DM Mono',monospace",fontSize:19,fontWeight:600,color:typeof c.v==='number'?sc(c.v):'#f2f2f7'}}>{c.v}</div><div style={{fontSize:9,color:'rgba(242,242,247,.35)',marginTop:3,textTransform:'uppercase',letterSpacing:'.06em'}}>{c.l}</div></div>))}</div>
    {(isInterp||s.type==='Scenario')&&<div style={{background:rl.bg,border:`1px solid ${rl.color}40`,borderRadius:10,padding:'11px 14px',marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:13,fontWeight:600,color:rl.color}}>{rl.label}</span><span style={{fontFamily:"'DM Mono',monospace",fontSize:18,fontWeight:600,color:rl.color}}>{s.overallScore||s.conf}</span></div><p style={{fontSize:11,color:rl.color,opacity:.7,marginTop:3,lineHeight:1.5}}>Readiness rating based on scenario performance</p></div>}
    <Lbl mt={0}>Coaching report</Lbl>
    <Card style={{marginBottom:12,minHeight:68}}>{loading&&<div style={{display:'flex',alignItems:'center',gap:9,fontSize:13,color:'rgba(242,242,247,.4)'}}><span style={{width:13,height:13,border:'1.5px solid rgba(255,255,255,.1)',borderTopColor:'rgba(242,242,247,.5)',borderRadius:'50%',animation:'spin .8s linear infinite',flexShrink:0,display:'inline-block'}}/>Generating your coaching report...</div>}{err&&<p style={{fontSize:13,color:'#FF453A'}}>{err}</p>}{report&&<div style={{fontSize:13,lineHeight:1.85,color:'#f2f2f7',whiteSpace:'pre-wrap'}}>{report}</div>}{!loading&&!report&&!err&&<p style={{fontSize:13,color:'rgba(242,242,247,.3)'}}>Click below to generate your AI coaching report.</p>}</Card>
    <button onClick={gen}disabled={loading}style={{display:'flex',alignItems:'center',gap:8,padding:'9px 20px',background:loading?'rgba(255,255,255,.07)':'#0A84FF',color:loading?'rgba(242,242,247,.4)':'#fff',border:'none',borderRadius:10,fontSize:13,fontWeight:600,cursor:loading?'not-allowed':'pointer'}}>{loading&&<span style={{width:13,height:13,border:'1.5px solid rgba(255,255,255,.1)',borderTopColor:'rgba(242,242,247,.5)',borderRadius:'50%',animation:'spin .8s linear infinite',flexShrink:0,display:'inline-block'}}/>}{report?'Regenerate report':'Generate coaching report'}</button>
    {s.transcript&&(<><Lbl>Session transcript</Lbl><div style={{background:'rgba(255,255,255,.04)',borderRadius:10,padding:'11px 13px',maxHeight:130,overflowY:'auto'}}><p style={{fontSize:11,fontFamily:"'DM Mono',monospace",lineHeight:1.7,color:'rgba(242,242,247,.35)',wordBreak:'break-word'}}>{s.transcript}</p></div></>)}
  </div>);
}

function ProgressPage({sessions,onClear}){
  const cvs=uR(null);
  uE(()=>{const c=cvs.current;if(!c||sessions.length<2)return;const ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);const data=[...sessions].reverse();const pad={l:30,r:12,t:12,b:20},cW=W-pad.l-pad.r,cH=H-pad.t-pad.b;[0,50,100].forEach(v=>{const y=pad.t+cH-(v/100)*cH;ctx.strokeStyle='rgba(255,255,255,.06)';ctx.lineWidth=0.5;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke();ctx.fillStyle='rgba(242,242,247,.2)';ctx.font="9px 'DM Mono',monospace";ctx.textAlign='right';ctx.fillText(v,pad.l-3,y+3);});const pts=data.map((s,i)=>({x:pad.l+(i/(data.length-1))*cW,y:pad.t+cH-(s.conf/100)*cH}));ctx.strokeStyle='#0A84FF';ctx.lineWidth=2;ctx.beginPath();pts.forEach((p,i)=>i===0?ctx.moveTo(p.x,p.y):ctx.lineTo(p.x,p.y));ctx.stroke();pts.forEach(p=>{ctx.fillStyle='#0A84FF';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();});ctx.fillStyle='rgba(242,242,247,.2)';ctx.font="9px 'DM Mono',monospace";ctx.textAlign='center';data.forEach((s,i)=>{ctx.fillText(s.time||`S${i+1}`,pad.l+(i/(data.length-1))*cW,H-4);});},[sessions]);
  if(!sessions.length)return(<div style={{textAlign:'center',padding:'3rem 1rem',color:'rgba(242,242,247,.3)'}}><div style={{fontSize:28,marginBottom:10}}>◎</div><p style={{fontSize:13}}>No sessions yet.</p></div>);
  const avg=Math.round(sessions.reduce((a,b)=>a+b.conf,0)/sessions.length),best=Math.max(...sessions.map(s=>s.conf)),avgF=Math.round(sessions.reduce((a,b)=>a+(b.fluency||0),0)/sessions.length);
  return(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:8,marginBottom:14}}>{[{l:'Sessions',v:sessions.length,c:'#f2f2f7'},{l:'Avg confidence',v:avg,c:sc(avg)},{l:'Best session',v:best,c:sc(best)},{l:'Avg fluency',v:avgF,c:sc(avgF)}].map(x=>(<div key={x.l}style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:10,padding:'10px 12px',textAlign:'center'}}><div style={{fontFamily:"'DM Mono',monospace",fontSize:19,fontWeight:600,color:x.c}}>{x.v}</div><div style={{fontSize:9,color:'rgba(242,242,247,.35)',marginTop:3,textTransform:'uppercase',letterSpacing:'.06em'}}>{x.l}</div></div>))}</div>
    <Lbl mt={0}>Confidence trend</Lbl>
    <Card style={{marginBottom:14}}>{sessions.length>=2?<canvas ref={cvs}width={640}height={130}style={{width:'100%',height:130,display:'block'}}/>:<p style={{fontSize:12,color:'rgba(242,242,247,.3)',textAlign:'center',padding:'1rem'}}>Record 2+ sessions to see your trend.</p>}</Card>
    <Lbl>Session history</Lbl>
    <Card>{sessions.map((s,i)=>(<div key={s.id||i}style={{display:'flex',alignItems:'center',gap:9,padding:'6px 0',borderBottom:i<sessions.length-1?'1px solid rgba(255,255,255,.06)':'none',flexWrap:'wrap'}}><span style={{fontSize:11,fontFamily:"'DM Mono',monospace",color:'rgba(242,242,247,.3)',minWidth:44}}>{s.time}</span><span style={{fontSize:10,background:s.type==='Scenario'?'rgba(10,132,255,.15)':'rgba(255,255,255,.06)',color:s.type==='Scenario'?'#0A84FF':'rgba(242,242,247,.5)',padding:'2px 8px',borderRadius:10,fontWeight:500,whiteSpace:'nowrap',maxWidth:160,overflow:'hidden',textOverflow:'ellipsis'}}>{s.scenario||s.type}</span><div style={{flex:1,minWidth:40,height:4,background:'rgba(255,255,255,.07)',borderRadius:2,overflow:'hidden'}}><div style={{height:'100%',width:`${s.conf}%`,background:sc(s.conf),borderRadius:2}}/></div><span style={{fontFamily:"'DM Mono',monospace",fontSize:12,fontWeight:600,color:sc(s.conf),minWidth:22}}>{s.conf}</span><span style={{fontSize:11,color:'rgba(242,242,247,.3)',minWidth:50,textAlign:'right'}}>stress {s.stress}</span></div>))}</Card>
    <button onClick={onClear}style={{marginTop:12,padding:'7px 14px',background:'transparent',border:'1px solid rgba(255,255,255,.12)',borderRadius:10,fontSize:12,color:'rgba(242,242,247,.4)',cursor:'pointer'}}>Clear history</button>
  </div>);
}

function ProfileSetup({onSave}){
  const[mode,setMode]=uS('clinician');const[f,setF]=uS({name:'',role:''});
  return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:'1.5rem',background:'#0a0a0f'}}>
    <div style={{width:'100%',maxWidth:440,background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.10)',borderRadius:20,padding:'28px'}}>
      <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:22}}><div style={{width:34,height:34,borderRadius:10,background:'#0A84FF',display:'flex',alignItems:'center',justifyContent:'center'}}><span style={{fontSize:18,fontWeight:700,color:'#fff'}}>K</span></div><div><div style={{fontSize:14,fontWeight:700,color:'#f2f2f7'}}>Kip Vocal Intelligence</div><div style={{fontSize:10,color:'rgba(242,242,247,.35)'}}>Medical Edition</div></div></div>
      <h2 style={{fontSize:20,fontWeight:700,color:'#f2f2f7',marginBottom:6}}>Who are you here as?</h2>
      <p style={{fontSize:12,color:'rgba(242,242,247,.45)',marginBottom:18,lineHeight:1.7}}>Your mode personalizes scenarios, scoring, and AI coaching.</p>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:18}}>
        {[{m:'clinician',icon:'🩺',label:'Clinician',sub:'Provider, interpreter, or healthcare professional',ac:'#0A84FF'},{m:'patient',icon:'🙋',label:'Patient',sub:'Patient or caregiver building communication confidence',ac:'#30D158'}].map(x=>(<div key={x.m}onClick={()=>{setMode(x.m);setF(p=>({...p,role:''}));}}style={{background:mode===x.m?`${x.ac}18`:'rgba(255,255,255,.04)',border:`1.5px solid ${mode===x.m?x.ac:'rgba(255,255,255,.09)'}`,borderRadius:12,padding:'14px 12px',cursor:'pointer',textAlign:'center',transition:'all .15s'}}><div style={{fontSize:20,marginBottom:4}}>{x.icon}</div><div style={{fontSize:13,fontWeight:600,color:mode===x.m?x.ac:'#f2f2f7'}}>{x.label}</div><div style={{fontSize:10,color:'rgba(242,242,247,.35)',marginTop:2,lineHeight:1.4}}>{x.sub}</div></div>))}
      </div>
      <div style={{display:'flex',flexDirection:'column',gap:11}}>
        <div><div style={{fontSize:9,fontWeight:700,letterSpacing:'.07em',textTransform:'uppercase',color:'rgba(242,242,247,.35)',marginBottom:5}}>Your name</div><input value={f.name}onChange={e=>setF(p=>({...p,name:e.target.value}))}placeholder="Enter your name"style={{width:'100%',padding:'9px 12px',fontSize:13,border:'1px solid rgba(255,255,255,.12)',borderRadius:10,background:'rgba(255,255,255,.06)',color:'#f2f2f7',outline:'none'}}/></div>
        <div><div style={{fontSize:9,fontWeight:700,letterSpacing:'.07em',textTransform:'uppercase',color:'rgba(242,242,247,.35)',marginBottom:5}}>Role</div><select value={f.role}onChange={e=>setF(p=>({...p,role:e.target.value}))}style={{width:'100%',padding:'9px 12px',fontSize:13,border:'1px solid rgba(255,255,255,.12)',borderRadius:10,background:'#1c1c26',color:f.role?'#f2f2f7':'rgba(242,242,247,.3)',outline:'none'}}><option value="">Select your role</option>{(mode==='clinician'?ROLES_C:ROLES_P).map(r=><option key={r}value={r}>{r}</option>)}</select></div>
        <button onClick={()=>{if(!f.name.trim())return alert('Please enter your name.');onSave({...f,mode,created:new Date().toISOString()});}}style={{padding:'10px 22px',background:'#0A84FF',color:'#fff',border:'none',borderRadius:10,fontSize:13,fontWeight:600,cursor:'pointer',marginTop:4}}>Get started</button>
        <p style={{fontSize:11,color:'rgba(242,242,247,.25)',textAlign:'center',lineHeight:1.6}}>All data stays on your device. No account required.</p>
      </div>
    </div>
  </div>);
}

const TABS=[{id:'live',label:'Live analyzer'},{id:'scenario',label:'Scenarios'},{id:'coach',label:'AI coaching'},{id:'progress',label:'Progress'}];

export default function App(){
  const[profile,setProfile]=useState(()=>loadLS('kvm_profile',null));
  const[sessions,setSessions]=useState(()=>loadLS('kvm_sessions',[]));
  const[tab,setTab]=useState('live');
  const[last,setLast]=useState(null);
  const saveProfile=p=>{setProfile(p);saveLS('kvm_profile',p);};
  const clearAll=()=>{if(!confirm('Clear profile and all sessions?'))return;setProfile(null);setSessions([]);setLast(null);localStorage.removeItem('kvm_profile');localStorage.removeItem('kvm_sessions');};
  const onEnd=d=>{const e={id:Date.now(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),ts:Date.now(),...d};setSessions(prev=>{const n=[e,...prev].slice(0,50);saveLS('kvm_sessions',n);return n;});setLast(e);setTimeout(()=>setTab('coach'),350);};
  const mC=profile?.mode==='patient'?'#30D158':'#0A84FF';
  if(!profile)return <ProfileSetup onSave={saveProfile}/>;
  return(<div style={{minHeight:'100vh',background:'#0a0a0f'}}>
    <div style={{background:'rgba(10,10,15,.95)',borderBottom:'1px solid rgba(255,255,255,.08)',padding:'0 18px',position:'sticky',top:0,zIndex:100}}>
      <div style={{maxWidth:680,margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between',height:50}}>
        <div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:28,height:28,borderRadius:8,background:'#0A84FF',display:'flex',alignItems:'center',justifyContent:'center'}}><span style={{fontSize:14,fontWeight:700,color:'#fff'}}>K</span></div><div><div style={{fontSize:13,fontWeight:700,color:'#f2f2f7',lineHeight:1.2}}>Kip Vocal Intelligence</div><div style={{fontSize:10,color:'rgba(242,242,247,.35)'}}>Medical · {profile.mode==='patient'?'Patient Mode':'Clinician Mode'}</div></div></div>
        <div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:26,height:26,borderRadius:'50%',background:`${mC}22`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:10,fontWeight:700,color:mC}}>{profile.name.split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase()}</div><button onClick={clearAll}style={{fontSize:11,color:'rgba(242,242,247,.3)',background:'none',border:'none',cursor:'pointer'}}>Reset</button></div>
      </div>
      <div style={{maxWidth:680,margin:'0 auto',display:'flex',overflowX:'auto'}}>{TABS.map(t=>(<button key={t.id}onClick={()=>setTab(t.id)}style={{padding:'7px 14px',fontSize:12,fontWeight:500,color:tab===t.id?'#f2f2f7':'rgba(242,242,247,.35)',background:'transparent',border:'none',borderBottom:`2px solid ${tab===t.id?mC:'transparent'}`,cursor:'pointer',whiteSpace:'nowrap',transition:'all .15s'}}>{t.label}</button>))}</div>
    </div>
    <div style={{maxWidth:680,margin:'0 auto',padding:'18px 16px 64px'}}>
      {tab==='live'&&<LivePage profile={profile}onEnd={onEnd}/>}
      {tab==='scenario'&&<ScenarioPage profile={profile}onEnd={onEnd}/>}
      {tab==='coach'&&<CoachPage last={last||sessions[0]||null}profile={profile}/>}
      {tab==='progress'&&<ProgressPage sessions={sessions}onClear={()=>{setSessions([]);saveLS('kvm_sessions',[]);}}/>}
    </div>
  </div>);
}
